http:
  image: nginx
  volumes:
    - ./provision/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./provision/nginx/conf.d/:/etc/nginx/conf.d/
    - ./provision/nginx/sites-enabled-dev/:/etc/nginx/sites-enabled/
    - ./:/opt/web/
  environment:
    - VIRTUAL_HOST=test.local
builder:
  image:    kendu/projectbuilder
  command: gulp
  ports:
    - 35729:35729
  volumes:
    - ./:/opt/web
  working_dir: /opt/web
