http:
  image: nginx
  environment:
    - VIRTUAL_HOST=test.local
  volumes:
    - ./provision/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./:/opt/web
  links:
    - app:app
app:
  image: kendu/php:7.0
  volumes:
    - ./:/opt/web
    - ./provision/php/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./provision/php/pool.conf:/etc/php5/fpm/pool.d/dev.conf
    - ./provision/php/php.ini:/etc/php5/fpm/conf.d/99.custom.ini
