http:
  image: nginx
  volumes:
    - ./provision/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./provision/nginx/sites-enabled:/etc/nginx/sites-enabled
    - /etc/localtime:/etc/localtime:ro
    - ./:/opt/web
  environment:
    - VIRTUAL_HOST=test.local
builder:
  image:    kendu/projectbuilder
  command: gulp
  ports:
    - 35729:35729
  volumes:
    - ./:/opt/web
  working_dir: /opt/web
