http:
  image: nginx
  volumes:
    - ./provision/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./provision/nginx/conf.d/:/etc/nginx/conf.d/
    - ./provision/nginx/sites-enabled-dev/:/etc/nginx/sites-enabled/
    - ./:/opt/web/
    - ./provision/certs:/opt/certs
  environment:
    - VIRTUAL_HOST=test.local
  links:
    - node-proxy
  ports:
    - 0.0.0.0:443:443
node-proxy:
  image:    kendu/projectbuilder
  command: node server.js
  volumes:
    - ./:/opt/web
  working_dir: /opt/web
